name: ieee_mvp
description: An entry to the IEEE contest.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^2.1.1
  equatable: ^0.6.1
  shared_preferences: ^0.5.3+4
  location: ^2.3.5
  geocoder: ^0.2.1
  flutter_slidable: ^0.5.4
  sqflite: ^1.1.6
  get_it: ^2.0.1
  dartz: ^0.8.6
  connectivity: ^0.4.5+3
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  path_provider: ^0.5.0+1
  firebase_messaging: ^6.0.1
  cloud_firestore: ^0.12.10+2
  google_maps_flutter: ^0.5.21+12
  firebase_analytics: ^5.0.6
  firebase_auth: ^0.15.0+1
  unicorndial: ^1.1.5
  font_awesome_flutter: ^8.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  moor_generator: ^1.5.0
  build_runner:

flutter:
  uses-material-design: true